-- ============================================================
-- Point Club — Phase 8 Database Migration
-- AI Agents, Team Workspaces, Smart Whiteboard, Learning,
-- Automation, Public API, Certifications, Globalization
-- ============================================================

-- ── AI Agent Conversations ───────────────────────────────────

CREATE TABLE IF NOT EXISTS agent_conversations (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  room_id       text        REFERENCES rooms(id) ON DELETE SET NULL,
  agent_type    text        NOT NULL
                CHECK (agent_type IN ('sketch_mentor','concept_artist','brainstorm_partner','color_expert','story_builder','design_reviewer','room_assistant')),
  title         text,
  messages      jsonb       NOT NULL DEFAULT '[]', -- [{role,content,ts}]
  context_data  jsonb       DEFAULT '{}',          -- canvas snapshot, etc.
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ac_user_idx  ON agent_conversations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ac_room_idx  ON agent_conversations(room_id);

-- Room AI notes (summaries, action items generated by room assistant)
CREATE TABLE IF NOT EXISTS room_ai_notes (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id    text        NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  type       text        NOT NULL DEFAULT 'summary'
             CHECK (type IN ('summary','action_items','ideas','mind_map')),
  content    text        NOT NULL,
  generated_by text      DEFAULT 'claude',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ── Team Workspaces ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS workspaces (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text        NOT NULL,
  slug         text        UNIQUE NOT NULL,
  description  text,
  avatar_url   text,
  owner_id     uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  plan         text        NOT NULL DEFAULT 'free' CHECK (plan IN ('free','team','enterprise')),
  member_limit integer     NOT NULL DEFAULT 5,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ws_owner_idx ON workspaces(owner_id);

CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id uuid   NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id      uuid   NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  role         text   NOT NULL DEFAULT 'member'
               CHECK (role IN ('owner','admin','member','viewer','guest')),
  invited_by   uuid   REFERENCES profiles(id),
  joined_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS workspace_invites (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email        text        NOT NULL,
  role         text        NOT NULL DEFAULT 'member',
  token        text        UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,
  invited_by   uuid        REFERENCES profiles(id),
  expires_at   timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  accepted_at  timestamptz
);

-- ── Projects & Tasks (Kanban) ─────────────────────────────────

CREATE TABLE IF NOT EXISTS projects (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name         text        NOT NULL,
  description  text,
  cover_color  text        DEFAULT '#7c5cbf',
  status       text        NOT NULL DEFAULT 'active'
               CHECK (status IN ('active','archived','completed')),
  owner_id     uuid        REFERENCES profiles(id),
  due_date     date,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS proj_ws_idx ON projects(workspace_id);

CREATE TABLE IF NOT EXISTS tasks (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title        text        NOT NULL,
  description  text,
  status       text        NOT NULL DEFAULT 'todo'
               CHECK (status IN ('todo','in_progress','review','done')),
  priority     text        NOT NULL DEFAULT 'medium'
               CHECK (priority IN ('low','medium','high','urgent')),
  assignee_id  uuid        REFERENCES profiles(id),
  created_by   uuid        REFERENCES profiles(id),
  due_date     date,
  sort_order   integer     NOT NULL DEFAULT 0,
  tags         text[]      DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS task_proj_idx   ON tasks(project_id, status);
CREATE INDEX IF NOT EXISTS task_assign_idx ON tasks(assignee_id);

-- ── Smart Whiteboard Elements ─────────────────────────────────

CREATE TABLE IF NOT EXISTS whiteboard_elements (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id      text        NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  type         text        NOT NULL
               CHECK (type IN ('sticky','shape','arrow','text','mindmap_node','flowchart_node','image','frame')),
  data         jsonb       NOT NULL DEFAULT '{}',
  position     jsonb       NOT NULL DEFAULT '{"x":0,"y":0}',
  size         jsonb       DEFAULT '{"w":200,"h":150}',
  style        jsonb       DEFAULT '{}',
  z_index      integer     NOT NULL DEFAULT 0,
  created_by   uuid        REFERENCES profiles(id),
  updated_by   uuid        REFERENCES profiles(id),
  locked_by    uuid        REFERENCES profiles(id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS we_room_idx ON whiteboard_elements(room_id);

-- ── Presentations ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS presentations (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id      text        NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  presenter_id uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title        text,
  slides       jsonb       DEFAULT '[]',   -- [{drawingId, notes}]
  is_live      boolean     NOT NULL DEFAULT false,
  viewer_count integer     NOT NULL DEFAULT 0,
  started_at   timestamptz,
  ended_at     timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ── Learning Hub ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS learning_courses (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  title        text        NOT NULL,
  description  text,
  thumbnail_url text,
  category     text        NOT NULL DEFAULT 'drawing',
  level        text        NOT NULL DEFAULT 'beginner'
               CHECK (level IN ('beginner','intermediate','advanced','expert')),
  type         text        NOT NULL DEFAULT 'course'
               CHECK (type IN ('course','workshop','tutorial','challenge')),
  duration_min integer     DEFAULT 0,
  lesson_count integer     DEFAULT 0,
  author_id    uuid        REFERENCES profiles(id),
  author_name  text,
  price_cents  integer     NOT NULL DEFAULT 0,
  xp_reward    integer     NOT NULL DEFAULT 100,
  is_published boolean     NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lc_category_idx ON learning_courses(category, is_published);

-- Seed default courses
INSERT INTO learning_courses (title, description, category, level, type, duration_min, lesson_count, author_name, xp_reward) VALUES
  ('Drawing Fundamentals',         'Master lines, shapes, and basic composition', 'drawing',     'beginner',      'course',    180, 12, 'Point Club Team', 200),
  ('Color Theory Essentials',      'Understanding hue, saturation, and contrast',  'color',       'intermediate',  'course',    120, 8,  'Point Club Team', 150),
  ('Character Design Crash Course','Create memorable characters from scratch',      'design',      'intermediate',  'course',    240, 16, 'Point Club Team', 300),
  ('Concept Art for Games',        'Environments, props, and character sheets',     'concept_art', 'advanced',      'course',    360, 20, 'Point Club Team', 400),
  ('Quick Sketching Techniques',   '30-second gesture drawings and warm-ups',       'drawing',     'beginner',      'workshop',  60,  6,  'Point Club Team', 80),
  ('UI/UX Wireframing',            'Prototyping interfaces with Point Club tools',  'design',      'intermediate',  'tutorial',  90,  5,  'Point Club Team', 120),
  ('Collaboration Skills',         'Getting the most out of multiplayer rooms',     'collaboration','beginner',      'workshop',  45,  4,  'Point Club Team', 60),
  ('AI-Assisted Creation',         'Using AI agents to supercharge your workflow',  'ai',          'intermediate',  'tutorial',  60,  6,  'Point Club Team', 150)
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS learning_lessons (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id    uuid        NOT NULL REFERENCES learning_courses(id) ON DELETE CASCADE,
  title        text        NOT NULL,
  content      text,
  video_url    text,
  duration_min integer     DEFAULT 0,
  sort_order   integer     NOT NULL DEFAULT 0,
  xp_reward    integer     NOT NULL DEFAULT 10
);

CREATE TABLE IF NOT EXISTS learning_enrollments (
  course_id     uuid        NOT NULL REFERENCES learning_courses(id) ON DELETE CASCADE,
  user_id       uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  progress      integer     NOT NULL DEFAULT 0,  -- 0-100
  completed_at  timestamptz,
  enrolled_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (course_id, user_id)
);
CREATE INDEX IF NOT EXISTS le_user_idx ON learning_enrollments(user_id);

-- ── Certifications ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS certifications (
  id           text        PRIMARY KEY,
  title        text        NOT NULL,
  description  text,
  icon         text        NOT NULL DEFAULT '🎓',
  criteria     jsonb       NOT NULL DEFAULT '{}',  -- {type, threshold}
  badge_color  text        DEFAULT '#7c5cbf'
);

INSERT INTO certifications (id, title, description, icon, criteria) VALUES
  ('creative_collaborator', 'Creative Collaborator',  'Drew in 10+ multiplayer rooms',        '🤝', '{"type":"rooms","count":10}'),
  ('concept_artist',        'Concept Artist',         'Published 25+ gallery drawings',        '🎨', '{"type":"gallery","count":25}'),
  ('community_mentor',      'Community Mentor',       'Helped 50+ community members',          '🏫', '{"type":"community_posts","count":50}'),
  ('challenge_champion',    'Challenge Champion',     'Completed 30+ daily challenges',        '🏆', '{"type":"challenges","count":30}'),
  ('ai_pioneer',            'AI Pioneer',             'Used AI agents 100+ times',             '🤖', '{"type":"ai_uses","count":100}'),
  ('world_builder',         'World Builder',          'Drew in 50+ world canvas sectors',      '🌍', '{"type":"sectors","count":50}'),
  ('marketplace_creator',   'Marketplace Creator',    'Published 5+ marketplace items',        '🛍️', '{"type":"marketplace_items","count":5}'),
  ('early_adopter_plus',    'Early Adopter Plus',     'Member since Phase 1',                  '⭐', '{"type":"account_age_days","count":1}')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_certifications (
  user_id       uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  cert_id       text        NOT NULL REFERENCES certifications(id) ON DELETE CASCADE,
  earned_at     timestamptz NOT NULL DEFAULT now(),
  evidence      jsonb       DEFAULT '{}',
  PRIMARY KEY (user_id, cert_id)
);

-- ── Public API Keys ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS api_keys (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name         text        NOT NULL,
  key_hash     text        UNIQUE NOT NULL,   -- SHA-256 of the actual key
  key_prefix   text        NOT NULL,          -- first 8 chars for display
  scopes       text[]      NOT NULL DEFAULT '{"read:drawings","read:profile"}',
  last_used_at timestamptz,
  expires_at   timestamptz,
  is_active    boolean     NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ak_user_idx ON api_keys(user_id);

CREATE TABLE IF NOT EXISTS webhook_subscriptions (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  url          text        NOT NULL,
  events       text[]      NOT NULL DEFAULT '{}',
  secret       text        NOT NULL,
  is_active    boolean     NOT NULL DEFAULT true,
  last_fired   timestamptz,
  fail_count   integer     NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ── Automation Workflows ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS automation_workflows (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  workspace_id uuid        REFERENCES workspaces(id) ON DELETE CASCADE,
  name         text        NOT NULL,
  trigger_type text        NOT NULL,  -- drawing_saved | challenge_completed | battle_won | schedule
  trigger_config jsonb     DEFAULT '{}',
  actions      jsonb       NOT NULL DEFAULT '[]',  -- [{type, config}]
  is_active    boolean     NOT NULL DEFAULT true,
  run_count    integer     NOT NULL DEFAULT 0,
  last_run_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS automation_runs (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_id     uuid        NOT NULL REFERENCES automation_workflows(id) ON DELETE CASCADE,
  status          text        NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','running','success','failed')),
  trigger_data    jsonb       DEFAULT '{}',
  output          jsonb       DEFAULT '{}',
  error           text,
  started_at      timestamptz NOT NULL DEFAULT now(),
  completed_at    timestamptz
);

-- ── Localization ──────────────────────────────────────────────

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS locale     text    DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS timezone   text    DEFAULT 'UTC',
  ADD COLUMN IF NOT EXISTS ai_credits integer NOT NULL DEFAULT 0;

-- ── RLS ──────────────────────────────────────────────────────

ALTER TABLE agent_conversations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_ai_notes         ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces            ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_members     ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_invites     ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects              ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE whiteboard_elements   ENABLE ROW LEVEL SECURITY;
ALTER TABLE presentations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_enrollments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_certifications   ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys              ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_workflows  ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_runs       ENABLE ROW LEVEL SECURITY;

-- AI conversations: own only
CREATE POLICY ac_select ON agent_conversations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY ac_insert ON agent_conversations FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY ac_update ON agent_conversations FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY ac_delete ON agent_conversations FOR DELETE USING (auth.uid() = user_id);

-- Room AI notes: room members
CREATE POLICY ran_select ON room_ai_notes FOR SELECT USING (true);

-- Workspaces: members only
CREATE POLICY ws_select ON workspaces FOR SELECT USING (
  auth.uid() = owner_id OR
  EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = id AND user_id = auth.uid())
);
CREATE POLICY ws_insert ON workspaces FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY ws_update ON workspaces FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY wm_select ON workspace_members FOR SELECT USING (
  user_id = auth.uid() OR
  EXISTS (SELECT 1 FROM workspaces WHERE id = workspace_id AND owner_id = auth.uid())
);
CREATE POLICY wm_all ON workspace_members FOR ALL USING (
  auth.uid() = user_id OR
  EXISTS (SELECT 1 FROM workspaces WHERE id = workspace_id AND owner_id = auth.uid())
);

-- Projects + Tasks: workspace members
CREATE POLICY proj_select ON projects FOR SELECT USING (
  EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = projects.workspace_id AND user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM workspaces WHERE id = projects.workspace_id AND owner_id = auth.uid())
);
CREATE POLICY proj_insert ON projects FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = workspace_id AND user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM workspaces WHERE id = workspace_id AND owner_id = auth.uid())
);
CREATE POLICY proj_update ON projects FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY task_select ON tasks FOR SELECT USING (true);
CREATE POLICY task_all    ON tasks FOR ALL    USING (auth.uid() = created_by OR auth.uid() = assignee_id);

-- Whiteboard: public room members
CREATE POLICY we_select ON whiteboard_elements FOR SELECT USING (true);
CREATE POLICY we_all    ON whiteboard_elements FOR ALL    USING (auth.role() = 'authenticated');

-- Learning
CREATE POLICY le_all ON learning_enrollments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY uc_all ON user_certifications  FOR ALL USING (auth.uid() = user_id);
CREATE POLICY uc_select ON user_certifications FOR SELECT USING (true);

-- API keys
CREATE POLICY ak_all ON api_keys FOR ALL USING (auth.uid() = user_id);
CREATE POLICY wb_all ON webhook_subscriptions FOR ALL USING (auth.uid() = user_id);

-- Automation
CREATE POLICY auto_all ON automation_workflows FOR ALL USING (auth.uid() = user_id);
CREATE POLICY run_select ON automation_runs FOR SELECT USING (
  EXISTS (SELECT 1 FROM automation_workflows WHERE id = workflow_id AND user_id = auth.uid())
);
